name: goreleaser

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - uses: actions/setup-node@v1
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          node-version: "12.x"
      - name: Bump version and Generate Changelog
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          npx standard-version -no-verify
          git remote rm origin
          git remote add origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git push --follow-tags origin HEAD:master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_ACTOR: ${{github.actor}}
          GITHUB_REPOSITORY: ${{github.repository}}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --release-notes CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
